apiVersion: v1
kind: ReplicationController
metadata:
  name: couchdb-rc
spec:
  replicas: 1
  selector:
    app: couchdb-pod
  template:
    metadata:
      labels:
        app: couchdb-pod
    spec:
      containers:
      - name: couchdb
        image: couchdb:1.6
        volumeMounts:
        - mountPath: /usr/local/var/lib/couchdb
          name: couchdb-volume
        ports:
        - containerPort: 5984
          name: api
      volumes:
      - name: couchdb-volume
        emptyDir: {}
