apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: couch
  name: couchdb-rc
spec:
  replicas: 1
  selector:
    app: couchdb-pod
  template:
    metadata:
      labels:
        app: couchdb-pod
    spec:
      containers:
      - name: couchdb
        image: couchdb:1.6
        volumeMounts:
        - mountPath: /usr/local/var/lib/couchdb
          name: couchdb-volume
        ports:
        - containerPort: 5984
          name: api
      volumes:
      - name: couchdb-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: couch
  labels:
    name: couch
spec:
  type: LoadBalancer
  ports:
    - port: 5984
      targetPort: 5984
      protocol: TCP
  selector:
    name: couch
