apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb-rc
spec:
  replicas: 1
  selector:
    app: influxdb-pod
  template:
    metadata:
      labels:
        app: influxdb-pod
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.1
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-volume
        ports:
        - containerPort: 8086
          name: api
        - containerPort: 8083
          name: admin
      volumes:
      - name: influxdb-volume
        emptyDir: {}
