apiVersion: v1
kind: Service
metadata:
  name: terse
  labels:
    name: terse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    name: terse
